// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/orderinfo.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetorderinfoListsReq struct {
	// 返回数量
	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// 返回数据开始数
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// 检索订单ID
	ID int64 `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	// 检索订单商品ID
	CID int64 `protobuf:"varint,4,opt,name=CID,proto3" json:"CID,omitempty"`
	// 订单状态
	Status int64 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	// 检索支付ID
	PID int64 `protobuf:"varint,6,opt,name=PID,proto3" json:"PID,omitempty"`
	// 开始时间
	StartTime int64 `protobuf:"varint,7,opt,name=startTime,proto3" json:"startTime,omitempty"`
	// 结束时间
	EndTime              int64    `protobuf:"varint,8,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetorderinfoListsReq) Reset()         { *m = GetorderinfoListsReq{} }
func (m *GetorderinfoListsReq) String() string { return proto.CompactTextString(m) }
func (*GetorderinfoListsReq) ProtoMessage()    {}
func (*GetorderinfoListsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24199a5abd600963, []int{0}
}

func (m *GetorderinfoListsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetorderinfoListsReq.Unmarshal(m, b)
}
func (m *GetorderinfoListsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetorderinfoListsReq.Marshal(b, m, deterministic)
}
func (m *GetorderinfoListsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetorderinfoListsReq.Merge(m, src)
}
func (m *GetorderinfoListsReq) XXX_Size() int {
	return xxx_messageInfo_GetorderinfoListsReq.Size(m)
}
func (m *GetorderinfoListsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetorderinfoListsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetorderinfoListsReq proto.InternalMessageInfo

func (m *GetorderinfoListsReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetorderinfoListsReq) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetorderinfoListsReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GetorderinfoListsReq) GetCID() int64 {
	if m != nil {
		return m.CID
	}
	return 0
}

func (m *GetorderinfoListsReq) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetorderinfoListsReq) GetPID() int64 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *GetorderinfoListsReq) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GetorderinfoListsReq) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type GetorderinfoListsResp struct {
	// 返回码 200:成功 500:失败
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// 错误信息
	Err string `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	// 检索数据总数
	Allnum int64 `protobuf:"varint,3,opt,name=Allnum,proto3" json:"Allnum,omitempty"`
	// 数据数列
	Data                 []*OrderinfoInfo `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetorderinfoListsResp) Reset()         { *m = GetorderinfoListsResp{} }
func (m *GetorderinfoListsResp) String() string { return proto.CompactTextString(m) }
func (*GetorderinfoListsResp) ProtoMessage()    {}
func (*GetorderinfoListsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_24199a5abd600963, []int{1}
}

func (m *GetorderinfoListsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetorderinfoListsResp.Unmarshal(m, b)
}
func (m *GetorderinfoListsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetorderinfoListsResp.Marshal(b, m, deterministic)
}
func (m *GetorderinfoListsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetorderinfoListsResp.Merge(m, src)
}
func (m *GetorderinfoListsResp) XXX_Size() int {
	return xxx_messageInfo_GetorderinfoListsResp.Size(m)
}
func (m *GetorderinfoListsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetorderinfoListsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetorderinfoListsResp proto.InternalMessageInfo

func (m *GetorderinfoListsResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetorderinfoListsResp) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetorderinfoListsResp) GetAllnum() int64 {
	if m != nil {
		return m.Allnum
	}
	return 0
}

func (m *GetorderinfoListsResp) GetData() []*OrderinfoInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrderinfoInfo struct {
	// 订单ID
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// 商品ID
	CID int64 `protobuf:"varint,2,opt,name=CID,proto3" json:"CID,omitempty"`
	// 支付ID
	PID int64 `protobuf:"varint,3,opt,name=PID,proto3" json:"PID,omitempty"`
	// 订单支付价钱
	CPrice int64 `protobuf:"varint,4,opt,name=CPrice,proto3" json:"CPrice,omitempty"`
	// 价钱说明
	Priceremark int64 `protobuf:"varint,5,opt,name=Priceremark,proto3" json:"Priceremark,omitempty"`
	// 创建时间
	CreateTime int64 `protobuf:"varint,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	// 订单状态
	Status               int64    `protobuf:"varint,7,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderinfoInfo) Reset()         { *m = OrderinfoInfo{} }
func (m *OrderinfoInfo) String() string { return proto.CompactTextString(m) }
func (*OrderinfoInfo) ProtoMessage()    {}
func (*OrderinfoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_24199a5abd600963, []int{2}
}

func (m *OrderinfoInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderinfoInfo.Unmarshal(m, b)
}
func (m *OrderinfoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderinfoInfo.Marshal(b, m, deterministic)
}
func (m *OrderinfoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderinfoInfo.Merge(m, src)
}
func (m *OrderinfoInfo) XXX_Size() int {
	return xxx_messageInfo_OrderinfoInfo.Size(m)
}
func (m *OrderinfoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderinfoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderinfoInfo proto.InternalMessageInfo

func (m *OrderinfoInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *OrderinfoInfo) GetCID() int64 {
	if m != nil {
		return m.CID
	}
	return 0
}

func (m *OrderinfoInfo) GetPID() int64 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *OrderinfoInfo) GetCPrice() int64 {
	if m != nil {
		return m.CPrice
	}
	return 0
}

func (m *OrderinfoInfo) GetPriceremark() int64 {
	if m != nil {
		return m.Priceremark
	}
	return 0
}

func (m *OrderinfoInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *OrderinfoInfo) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type CreateOrderReq struct {
	// 商品ID
	CID int64 `protobuf:"varint,1,opt,name=CID,proto3" json:"CID,omitempty"`
	// 商品价钱
	Newprice             int64    `protobuf:"varint,2,opt,name=newprice,proto3" json:"newprice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderReq) Reset()         { *m = CreateOrderReq{} }
func (m *CreateOrderReq) String() string { return proto.CompactTextString(m) }
func (*CreateOrderReq) ProtoMessage()    {}
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24199a5abd600963, []int{3}
}

func (m *CreateOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderReq.Unmarshal(m, b)
}
func (m *CreateOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderReq.Marshal(b, m, deterministic)
}
func (m *CreateOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderReq.Merge(m, src)
}
func (m *CreateOrderReq) XXX_Size() int {
	return xxx_messageInfo_CreateOrderReq.Size(m)
}
func (m *CreateOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderReq proto.InternalMessageInfo

func (m *CreateOrderReq) GetCID() int64 {
	if m != nil {
		return m.CID
	}
	return 0
}

func (m *CreateOrderReq) GetNewprice() int64 {
	if m != nil {
		return m.Newprice
	}
	return 0
}

type CreateOrderResp struct {
	// 返回码 200:成功 500:失败
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// 错误信息
	Err string `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	// 订单ID
	ID                   int64    `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResp) Reset()         { *m = CreateOrderResp{} }
func (m *CreateOrderResp) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResp) ProtoMessage()    {}
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_24199a5abd600963, []int{4}
}

func (m *CreateOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResp.Unmarshal(m, b)
}
func (m *CreateOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResp.Marshal(b, m, deterministic)
}
func (m *CreateOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResp.Merge(m, src)
}
func (m *CreateOrderResp) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResp.Size(m)
}
func (m *CreateOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResp proto.InternalMessageInfo

func (m *CreateOrderResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateOrderResp) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *CreateOrderResp) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DelOrderReq struct {
	// 订单ID
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelOrderReq) Reset()         { *m = DelOrderReq{} }
func (m *DelOrderReq) String() string { return proto.CompactTextString(m) }
func (*DelOrderReq) ProtoMessage()    {}
func (*DelOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24199a5abd600963, []int{5}
}

func (m *DelOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelOrderReq.Unmarshal(m, b)
}
func (m *DelOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelOrderReq.Marshal(b, m, deterministic)
}
func (m *DelOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelOrderReq.Merge(m, src)
}
func (m *DelOrderReq) XXX_Size() int {
	return xxx_messageInfo_DelOrderReq.Size(m)
}
func (m *DelOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelOrderReq proto.InternalMessageInfo

func (m *DelOrderReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DelOrderResp struct {
	// 返回码 200:成功 500:失败
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// 错误信息
	Err                  string   `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelOrderResp) Reset()         { *m = DelOrderResp{} }
func (m *DelOrderResp) String() string { return proto.CompactTextString(m) }
func (*DelOrderResp) ProtoMessage()    {}
func (*DelOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_24199a5abd600963, []int{6}
}

func (m *DelOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelOrderResp.Unmarshal(m, b)
}
func (m *DelOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelOrderResp.Marshal(b, m, deterministic)
}
func (m *DelOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelOrderResp.Merge(m, src)
}
func (m *DelOrderResp) XXX_Size() int {
	return xxx_messageInfo_DelOrderResp.Size(m)
}
func (m *DelOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelOrderResp proto.InternalMessageInfo

func (m *DelOrderResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DelOrderResp) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*GetorderinfoListsReq)(nil), "proto.GetorderinfoListsReq")
	proto.RegisterType((*GetorderinfoListsResp)(nil), "proto.GetorderinfoListsResp")
	proto.RegisterType((*OrderinfoInfo)(nil), "proto.orderinfoInfo")
	proto.RegisterType((*CreateOrderReq)(nil), "proto.CreateOrderReq")
	proto.RegisterType((*CreateOrderResp)(nil), "proto.CreateOrderResp")
	proto.RegisterType((*DelOrderReq)(nil), "proto.DelOrderReq")
	proto.RegisterType((*DelOrderResp)(nil), "proto.DelOrderResp")
}

func init() { proto.RegisterFile("proto/orderinfo.proto", fileDescriptor_24199a5abd600963) }

var fileDescriptor_24199a5abd600963 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdd, 0x8e, 0xd2, 0x40,
	0x14, 0x4e, 0x5b, 0x60, 0xe1, 0x74, 0xc5, 0x65, 0x04, 0x6c, 0x2a, 0x1a, 0x32, 0x57, 0x64, 0x2f,
	0xb6, 0xc9, 0xea, 0x95, 0x17, 0x26, 0x86, 0x2a, 0x69, 0x62, 0x22, 0xa9, 0xfa, 0x00, 0x55, 0xa6,
	0x9b, 0xc6, 0xd2, 0xa9, 0x33, 0xb3, 0xf1, 0xd2, 0xc4, 0x47, 0xd0, 0x67, 0xf1, 0x1d, 0xbc, 0xf7,
	0x15, 0x7c, 0x10, 0xd3, 0x33, 0x43, 0x5b, 0x58, 0x4c, 0xb8, 0xe2, 0x7c, 0xdf, 0xf9, 0x99, 0xef,
	0x7c, 0xa7, 0xc0, 0xa4, 0x14, 0x5c, 0xf1, 0x80, 0x8b, 0x0d, 0x13, 0x59, 0x91, 0xf2, 0x2b, 0xc4,
	0xa4, 0x8b, 0x3f, 0xfe, 0xec, 0x86, 0xf3, 0x9b, 0x9c, 0x05, 0x49, 0x99, 0x05, 0x49, 0x51, 0x70,
	0x95, 0xa8, 0x8c, 0x17, 0x52, 0x17, 0xd1, 0xdf, 0x16, 0x8c, 0x57, 0x4c, 0xd5, 0xbd, 0x6f, 0x32,
	0xa9, 0x64, 0xcc, 0xbe, 0x90, 0x31, 0x74, 0xf3, 0x6c, 0x9b, 0x29, 0xcf, 0x9a, 0x5b, 0x0b, 0x27,
	0xd6, 0x80, 0x4c, 0xa1, 0xc7, 0xd3, 0x54, 0x32, 0xe5, 0xd9, 0x48, 0x1b, 0x44, 0x86, 0x60, 0x47,
	0xa1, 0xe7, 0x20, 0x67, 0x47, 0x21, 0xb9, 0x00, 0x67, 0x19, 0x85, 0x5e, 0x07, 0x89, 0x2a, 0xac,
	0x3a, 0xa5, 0x4a, 0xd4, 0xad, 0xf4, 0xba, 0xba, 0x53, 0xa3, 0xaa, 0x72, 0x1d, 0x85, 0x5e, 0x4f,
	0x57, 0xae, 0xa3, 0x90, 0xcc, 0x60, 0x20, 0x55, 0x22, 0xd4, 0xfb, 0x6c, 0xcb, 0xbc, 0x33, 0xe4,
	0x1b, 0x82, 0x78, 0x70, 0xc6, 0x8a, 0x0d, 0xe6, 0xfa, 0x98, 0xdb, 0x41, 0xfa, 0x0d, 0x26, 0x47,
	0x36, 0x91, 0x25, 0x21, 0xd0, 0x59, 0xf2, 0x0d, 0xc3, 0x4d, 0xba, 0x31, 0xc6, 0xd5, 0xb3, 0xaf,
	0x84, 0xc0, 0x2d, 0x06, 0x71, 0x15, 0x56, 0x02, 0x5f, 0xe6, 0x79, 0x71, 0xbb, 0x35, 0x6b, 0x18,
	0x44, 0x16, 0xd0, 0x09, 0x13, 0x95, 0x78, 0x9d, 0xb9, 0xb3, 0x70, 0xaf, 0xc7, 0xda, 0xb7, 0xab,
	0xfa, 0x99, 0xa8, 0x48, 0x79, 0x8c, 0x15, 0xf4, 0x97, 0x05, 0xf7, 0xf6, 0x78, 0x63, 0x8b, 0x75,
	0x68, 0x8b, 0xdd, 0xd8, 0x62, 0xd6, 0x77, 0x9a, 0xf5, 0xa7, 0xd0, 0x5b, 0xae, 0x45, 0xf6, 0x89,
	0x19, 0xf7, 0x0c, 0x22, 0x73, 0x70, 0x31, 0x10, 0x6c, 0x9b, 0x88, 0xcf, 0xc6, 0xc5, 0x36, 0x45,
	0x9e, 0x00, 0x2c, 0x05, 0x4b, 0x14, 0x43, 0x77, 0xb4, 0xa3, 0x2d, 0xa6, 0x9a, 0xfc, 0x4e, 0x9f,
	0x40, 0xbb, 0x6a, 0x10, 0x7d, 0x01, 0x43, 0x5d, 0xf5, 0xb6, 0x12, 0x5f, 0x1d, 0xdf, 0xe8, 0xb4,
	0x1a, 0x9d, 0x3e, 0xf4, 0x0b, 0xf6, 0xb5, 0x44, 0x5d, 0x5a, 0x7e, 0x8d, 0xe9, 0x0a, 0xee, 0xef,
	0xf5, 0x9f, 0x6c, 0xf9, 0xc1, 0x57, 0x43, 0x1f, 0x83, 0x1b, 0xb2, 0xbc, 0x56, 0x71, 0xe0, 0x1e,
	0x7d, 0x06, 0xe7, 0x4d, 0xfa, 0xd4, 0x47, 0xae, 0x7f, 0xd8, 0x30, 0xa8, 0xaf, 0x42, 0x52, 0x18,
	0xdd, 0xf9, 0x48, 0xc8, 0x23, 0x73, 0xd4, 0x63, 0x7f, 0x04, 0x7f, 0xf6, 0xff, 0xa4, 0x2c, 0xe9,
	0xf4, 0xfb, 0x9f, 0xbf, 0x3f, 0xed, 0x0b, 0x32, 0x0c, 0x56, 0x4c, 0xa1, 0x34, 0x3d, 0xf2, 0x03,
	0xb8, 0x2d, 0x4f, 0xc8, 0xc4, 0x0c, 0xd9, 0xf7, 0xd9, 0x9f, 0x1e, 0xa3, 0x65, 0x49, 0x1f, 0xe2,
	0xd4, 0x11, 0x3d, 0x0f, 0x5a, 0x99, 0xe7, 0xd6, 0x25, 0x79, 0x0d, 0xfd, 0x9d, 0x05, 0x84, 0x98,
	0xe6, 0x96, 0x65, 0xfe, 0x83, 0x3b, 0x9c, 0x2c, 0xe9, 0x08, 0xa7, 0xb9, 0x97, 0x83, 0x60, 0x47,
	0x7f, 0xec, 0x61, 0xd9, 0xd3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x45, 0x7c, 0x5b, 0x21, 0x3b,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderinfoClient is the client API for Orderinfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderinfoClient interface {
	//获取订单列表
	GetorderinfoLists(ctx context.Context, in *GetorderinfoListsReq, opts ...grpc.CallOption) (*GetorderinfoListsResp, error)
	//创建订单
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
	//删除订单
	DelOrder(ctx context.Context, in *DelOrderReq, opts ...grpc.CallOption) (*DelOrderResp, error)
}

type orderinfoClient struct {
	cc *grpc.ClientConn
}

func NewOrderinfoClient(cc *grpc.ClientConn) OrderinfoClient {
	return &orderinfoClient{cc}
}

func (c *orderinfoClient) GetorderinfoLists(ctx context.Context, in *GetorderinfoListsReq, opts ...grpc.CallOption) (*GetorderinfoListsResp, error) {
	out := new(GetorderinfoListsResp)
	err := c.cc.Invoke(ctx, "/proto.orderinfo/GetorderinfoLists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderinfoClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	out := new(CreateOrderResp)
	err := c.cc.Invoke(ctx, "/proto.orderinfo/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderinfoClient) DelOrder(ctx context.Context, in *DelOrderReq, opts ...grpc.CallOption) (*DelOrderResp, error) {
	out := new(DelOrderResp)
	err := c.cc.Invoke(ctx, "/proto.orderinfo/DelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderinfoServer is the server API for Orderinfo service.
type OrderinfoServer interface {
	//获取订单列表
	GetorderinfoLists(context.Context, *GetorderinfoListsReq) (*GetorderinfoListsResp, error)
	//创建订单
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderResp, error)
	//删除订单
	DelOrder(context.Context, *DelOrderReq) (*DelOrderResp, error)
}

func RegisterOrderinfoServer(s *grpc.Server, srv OrderinfoServer) {
	s.RegisterService(&_Orderinfo_serviceDesc, srv)
}

func _Orderinfo_GetorderinfoLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetorderinfoListsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderinfoServer).GetorderinfoLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.orderinfo/GetorderinfoLists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderinfoServer).GetorderinfoLists(ctx, req.(*GetorderinfoListsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orderinfo_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderinfoServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.orderinfo/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderinfoServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orderinfo_DelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderinfoServer).DelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.orderinfo/DelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderinfoServer).DelOrder(ctx, req.(*DelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Orderinfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.orderinfo",
	HandlerType: (*OrderinfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetorderinfoLists",
			Handler:    _Orderinfo_GetorderinfoLists_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Orderinfo_CreateOrder_Handler,
		},
		{
			MethodName: "DelOrder",
			Handler:    _Orderinfo_DelOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/orderinfo.proto",
}
