// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pay.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPayListReq struct {
	// 返回数量
	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// 返回数据开始数
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// 支付订单ID
	ID int64 `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	// 支付订单状态
	Status int64 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 支付方式
	Way int64 `protobuf:"varint,5,opt,name=way,proto3" json:"way,omitempty"`
	// 开始时间
	StartTime int64 `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	// 结束时间
	EndTime              int64    `protobuf:"varint,7,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPayListReq) Reset()         { *m = GetPayListReq{} }
func (m *GetPayListReq) String() string { return proto.CompactTextString(m) }
func (*GetPayListReq) ProtoMessage()    {}
func (*GetPayListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{0}
}

func (m *GetPayListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPayListReq.Unmarshal(m, b)
}
func (m *GetPayListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPayListReq.Marshal(b, m, deterministic)
}
func (m *GetPayListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPayListReq.Merge(m, src)
}
func (m *GetPayListReq) XXX_Size() int {
	return xxx_messageInfo_GetPayListReq.Size(m)
}
func (m *GetPayListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPayListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPayListReq proto.InternalMessageInfo

func (m *GetPayListReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetPayListReq) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetPayListReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GetPayListReq) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetPayListReq) GetWay() int64 {
	if m != nil {
		return m.Way
	}
	return 0
}

func (m *GetPayListReq) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GetPayListReq) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type GetPayListResp struct {
	// 返回码 200:成功 500:失败
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// 错误信息
	Err string `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	// 检索数据总数
	Allnum int64 `protobuf:"varint,3,opt,name=Allnum,proto3" json:"Allnum,omitempty"`
	// 数据数列
	Data                 []*GetPayListInfo `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetPayListResp) Reset()         { *m = GetPayListResp{} }
func (m *GetPayListResp) String() string { return proto.CompactTextString(m) }
func (*GetPayListResp) ProtoMessage()    {}
func (*GetPayListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{1}
}

func (m *GetPayListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPayListResp.Unmarshal(m, b)
}
func (m *GetPayListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPayListResp.Marshal(b, m, deterministic)
}
func (m *GetPayListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPayListResp.Merge(m, src)
}
func (m *GetPayListResp) XXX_Size() int {
	return xxx_messageInfo_GetPayListResp.Size(m)
}
func (m *GetPayListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPayListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetPayListResp proto.InternalMessageInfo

func (m *GetPayListResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetPayListResp) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetPayListResp) GetAllnum() int64 {
	if m != nil {
		return m.Allnum
	}
	return 0
}

func (m *GetPayListResp) GetData() []*GetPayListInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetPayListInfo struct {
	// 支付订单ID
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// 支付订单支付价钱
	Price int64 `protobuf:"varint,2,opt,name=Price,proto3" json:"Price,omitempty"`
	// 支付方式  1银行卡 2支付宝 3微信
	Way int64 `protobuf:"varint,3,opt,name=Way,proto3" json:"Way,omitempty"`
	// 支付账号
	Number string `protobuf:"bytes,4,opt,name=Number,proto3" json:"Number,omitempty"`
	// 支付订单状态
	Status int64 `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	// 创建时间
	CreateTime           int64    `protobuf:"varint,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPayListInfo) Reset()         { *m = GetPayListInfo{} }
func (m *GetPayListInfo) String() string { return proto.CompactTextString(m) }
func (*GetPayListInfo) ProtoMessage()    {}
func (*GetPayListInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{2}
}

func (m *GetPayListInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPayListInfo.Unmarshal(m, b)
}
func (m *GetPayListInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPayListInfo.Marshal(b, m, deterministic)
}
func (m *GetPayListInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPayListInfo.Merge(m, src)
}
func (m *GetPayListInfo) XXX_Size() int {
	return xxx_messageInfo_GetPayListInfo.Size(m)
}
func (m *GetPayListInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPayListInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GetPayListInfo proto.InternalMessageInfo

func (m *GetPayListInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GetPayListInfo) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GetPayListInfo) GetWay() int64 {
	if m != nil {
		return m.Way
	}
	return 0
}

func (m *GetPayListInfo) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *GetPayListInfo) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetPayListInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type CreatePayInfoReq struct {
	// 订单ID数组
	CIDs []int64 `protobuf:"varint,1,rep,packed,name=CIDs,proto3" json:"CIDs,omitempty"`
	// 订单总价钱
	Price                int64    `protobuf:"varint,2,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePayInfoReq) Reset()         { *m = CreatePayInfoReq{} }
func (m *CreatePayInfoReq) String() string { return proto.CompactTextString(m) }
func (*CreatePayInfoReq) ProtoMessage()    {}
func (*CreatePayInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{3}
}

func (m *CreatePayInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePayInfoReq.Unmarshal(m, b)
}
func (m *CreatePayInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePayInfoReq.Marshal(b, m, deterministic)
}
func (m *CreatePayInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePayInfoReq.Merge(m, src)
}
func (m *CreatePayInfoReq) XXX_Size() int {
	return xxx_messageInfo_CreatePayInfoReq.Size(m)
}
func (m *CreatePayInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePayInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePayInfoReq proto.InternalMessageInfo

func (m *CreatePayInfoReq) GetCIDs() []int64 {
	if m != nil {
		return m.CIDs
	}
	return nil
}

func (m *CreatePayInfoReq) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CreatePayInfoResp struct {
	// 返回码 200:成功 500:失败
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// 错误信息
	Err string `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	// 支付订单ID
	ID                   int64    `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePayInfoResp) Reset()         { *m = CreatePayInfoResp{} }
func (m *CreatePayInfoResp) String() string { return proto.CompactTextString(m) }
func (*CreatePayInfoResp) ProtoMessage()    {}
func (*CreatePayInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{4}
}

func (m *CreatePayInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePayInfoResp.Unmarshal(m, b)
}
func (m *CreatePayInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePayInfoResp.Marshal(b, m, deterministic)
}
func (m *CreatePayInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePayInfoResp.Merge(m, src)
}
func (m *CreatePayInfoResp) XXX_Size() int {
	return xxx_messageInfo_CreatePayInfoResp.Size(m)
}
func (m *CreatePayInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePayInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePayInfoResp proto.InternalMessageInfo

func (m *CreatePayInfoResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreatePayInfoResp) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *CreatePayInfoResp) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DelPayInfoReq struct {
	// 支付订单ID
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelPayInfoReq) Reset()         { *m = DelPayInfoReq{} }
func (m *DelPayInfoReq) String() string { return proto.CompactTextString(m) }
func (*DelPayInfoReq) ProtoMessage()    {}
func (*DelPayInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{5}
}

func (m *DelPayInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelPayInfoReq.Unmarshal(m, b)
}
func (m *DelPayInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelPayInfoReq.Marshal(b, m, deterministic)
}
func (m *DelPayInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelPayInfoReq.Merge(m, src)
}
func (m *DelPayInfoReq) XXX_Size() int {
	return xxx_messageInfo_DelPayInfoReq.Size(m)
}
func (m *DelPayInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelPayInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelPayInfoReq proto.InternalMessageInfo

func (m *DelPayInfoReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DelPayInfoResp struct {
	// 返回码 200:成功 500:失败
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// 错误信息
	Err                  string   `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelPayInfoResp) Reset()         { *m = DelPayInfoResp{} }
func (m *DelPayInfoResp) String() string { return proto.CompactTextString(m) }
func (*DelPayInfoResp) ProtoMessage()    {}
func (*DelPayInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{6}
}

func (m *DelPayInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelPayInfoResp.Unmarshal(m, b)
}
func (m *DelPayInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelPayInfoResp.Marshal(b, m, deterministic)
}
func (m *DelPayInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelPayInfoResp.Merge(m, src)
}
func (m *DelPayInfoResp) XXX_Size() int {
	return xxx_messageInfo_DelPayInfoResp.Size(m)
}
func (m *DelPayInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelPayInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelPayInfoResp proto.InternalMessageInfo

func (m *DelPayInfoResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DelPayInfoResp) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type PaySuccessReq struct {
	// 支付订单ID
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// 支付价钱
	Price int64 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	// 支付方式 1银行卡 2支付宝 3微信
	Way int64 `protobuf:"varint,3,opt,name=way,proto3" json:"way,omitempty"`
	// 支付账号
	Number string `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	// 支付流水号
	Serial               string   `protobuf:"bytes,5,opt,name=serial,proto3" json:"serial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaySuccessReq) Reset()         { *m = PaySuccessReq{} }
func (m *PaySuccessReq) String() string { return proto.CompactTextString(m) }
func (*PaySuccessReq) ProtoMessage()    {}
func (*PaySuccessReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{7}
}

func (m *PaySuccessReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaySuccessReq.Unmarshal(m, b)
}
func (m *PaySuccessReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaySuccessReq.Marshal(b, m, deterministic)
}
func (m *PaySuccessReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaySuccessReq.Merge(m, src)
}
func (m *PaySuccessReq) XXX_Size() int {
	return xxx_messageInfo_PaySuccessReq.Size(m)
}
func (m *PaySuccessReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PaySuccessReq.DiscardUnknown(m)
}

var xxx_messageInfo_PaySuccessReq proto.InternalMessageInfo

func (m *PaySuccessReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PaySuccessReq) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PaySuccessReq) GetWay() int64 {
	if m != nil {
		return m.Way
	}
	return 0
}

func (m *PaySuccessReq) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PaySuccessReq) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

type PaySuccessResp struct {
	// 返回码 200:成功 500:失败
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// 错误信息
	Err                  string   `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaySuccessResp) Reset()         { *m = PaySuccessResp{} }
func (m *PaySuccessResp) String() string { return proto.CompactTextString(m) }
func (*PaySuccessResp) ProtoMessage()    {}
func (*PaySuccessResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{8}
}

func (m *PaySuccessResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaySuccessResp.Unmarshal(m, b)
}
func (m *PaySuccessResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaySuccessResp.Marshal(b, m, deterministic)
}
func (m *PaySuccessResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaySuccessResp.Merge(m, src)
}
func (m *PaySuccessResp) XXX_Size() int {
	return xxx_messageInfo_PaySuccessResp.Size(m)
}
func (m *PaySuccessResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PaySuccessResp.DiscardUnknown(m)
}

var xxx_messageInfo_PaySuccessResp proto.InternalMessageInfo

func (m *PaySuccessResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PaySuccessResp) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPayListReq)(nil), "proto.GetPayListReq")
	proto.RegisterType((*GetPayListResp)(nil), "proto.GetPayListResp")
	proto.RegisterType((*GetPayListInfo)(nil), "proto.GetPayListInfo")
	proto.RegisterType((*CreatePayInfoReq)(nil), "proto.CreatePayInfoReq")
	proto.RegisterType((*CreatePayInfoResp)(nil), "proto.CreatePayInfoResp")
	proto.RegisterType((*DelPayInfoReq)(nil), "proto.DelPayInfoReq")
	proto.RegisterType((*DelPayInfoResp)(nil), "proto.DelPayInfoResp")
	proto.RegisterType((*PaySuccessReq)(nil), "proto.PaySuccessReq")
	proto.RegisterType((*PaySuccessResp)(nil), "proto.PaySuccessResp")
}

func init() { proto.RegisterFile("proto/pay.proto", fileDescriptor_6e5aad0ac58a7583) }

var fileDescriptor_6e5aad0ac58a7583 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe5, 0x38, 0x49, 0x95, 0x89, 0x12, 0xc2, 0x36, 0x2d, 0x26, 0xaa, 0x20, 0xda, 0x53,
	0xc8, 0xa1, 0x96, 0x8a, 0xc4, 0xa1, 0xe2, 0x82, 0x1a, 0x84, 0x2c, 0xa1, 0x2a, 0xb8, 0x48, 0x9c,
	0x38, 0x6c, 0xd3, 0x4d, 0x65, 0xc9, 0xb1, 0x1d, 0xef, 0x46, 0x91, 0xaf, 0xbc, 0x02, 0x17, 0xde,
	0x82, 0x87, 0xe1, 0xc0, 0x0b, 0xf0, 0x20, 0x68, 0x67, 0x37, 0xf6, 0x3a, 0xcd, 0x21, 0x27, 0xcf,
	0x3f, 0x33, 0x9e, 0xf9, 0xf7, 0xdb, 0x85, 0x67, 0x59, 0x9e, 0xca, 0xd4, 0xcf, 0x58, 0x71, 0x89,
	0x11, 0x69, 0xe1, 0x67, 0x74, 0xf1, 0x98, 0xa6, 0x8f, 0x31, 0xf7, 0x59, 0x16, 0xf9, 0x2c, 0x49,
	0x52, 0xc9, 0x64, 0x94, 0x26, 0x42, 0x37, 0xd1, 0xdf, 0x0e, 0xf4, 0x3e, 0x71, 0x39, 0x67, 0xc5,
	0xe7, 0x48, 0xc8, 0x90, 0xaf, 0xc9, 0x10, 0x5a, 0x71, 0xb4, 0x8a, 0xa4, 0xe7, 0x8c, 0x9d, 0x89,
	0x1b, 0x6a, 0x41, 0xce, 0xa1, 0x9d, 0x2e, 0x97, 0x82, 0x4b, 0xaf, 0x81, 0x69, 0xa3, 0x48, 0x1f,
	0x1a, 0xc1, 0xcc, 0x73, 0x31, 0xd7, 0x08, 0x66, 0xaa, 0x4f, 0x48, 0x26, 0x37, 0xc2, 0x6b, 0xea,
	0x3e, 0xad, 0xc8, 0x00, 0xdc, 0x2d, 0x2b, 0xbc, 0x16, 0x26, 0x55, 0x48, 0x2e, 0xa0, 0x23, 0x24,
	0xcb, 0xe5, 0xd7, 0x68, 0xc5, 0xbd, 0x36, 0xe6, 0xab, 0x04, 0xf1, 0xe0, 0x84, 0x27, 0x0f, 0x58,
	0x3b, 0xc1, 0xda, 0x4e, 0xd2, 0x02, 0xfa, 0xb6, 0x61, 0x91, 0x11, 0x02, 0xcd, 0x9b, 0xf4, 0x81,
	0xa3, 0xe1, 0x56, 0x88, 0xb1, 0xda, 0xf7, 0x31, 0xcf, 0xd1, 0x6c, 0x27, 0x54, 0xa1, 0x72, 0xf6,
	0x21, 0x8e, 0x93, 0xcd, 0xca, 0xb8, 0x35, 0x8a, 0xbc, 0x81, 0xe6, 0x8c, 0x49, 0xe6, 0x35, 0xc7,
	0xee, 0xa4, 0x7b, 0x75, 0xa6, 0xb9, 0x5c, 0x56, 0x2b, 0x82, 0x64, 0x99, 0x86, 0xd8, 0x42, 0x7f,
	0x39, 0xf6, 0x6e, 0x55, 0x30, 0xe7, 0x77, 0xca, 0xf3, 0x0f, 0xa1, 0x35, 0xcf, 0xa3, 0x05, 0x37,
	0x98, 0xb4, 0x50, 0x6e, 0xbe, 0xb1, 0xc2, 0x2c, 0x56, 0xa1, 0x72, 0x73, 0xbb, 0x59, 0xdd, 0xf3,
	0x1c, 0x39, 0x75, 0x42, 0xa3, 0x54, 0xfe, 0x4e, 0xf3, 0xd3, 0xa8, 0x8c, 0x22, 0xaf, 0x00, 0x6e,
	0x72, 0xce, 0x24, 0xb7, 0x70, 0x59, 0x19, 0xfa, 0x1e, 0x06, 0x5a, 0xcd, 0x59, 0x81, 0x8e, 0xf9,
	0x1a, 0xb9, 0x04, 0x33, 0xe1, 0x39, 0x63, 0x77, 0xe2, 0x86, 0x18, 0x1f, 0xf6, 0x47, 0x03, 0x78,
	0xbe, 0xf7, 0xf7, 0xd1, 0x58, 0xf7, 0x1e, 0x00, 0x7d, 0x0d, 0xbd, 0x19, 0x8f, 0x2d, 0x17, 0x7b,
	0x84, 0xe8, 0x3b, 0xe8, 0xdb, 0x0d, 0xc7, 0x2e, 0xa2, 0x5b, 0xe8, 0xcd, 0x59, 0x71, 0xb7, 0x59,
	0x2c, 0xb8, 0x10, 0x07, 0x06, 0xab, 0xa3, 0x65, 0xf6, 0xd1, 0xb2, 0x1d, 0xfa, 0x6d, 0x85, 0x7e,
	0xab, 0xd1, 0x27, 0x35, 0xf4, 0x49, 0x89, 0x5e, 0xf0, 0x3c, 0x62, 0x31, 0xa2, 0xef, 0x84, 0x46,
	0x29, 0xc3, 0xf6, 0xe2, 0x63, 0x0d, 0x5f, 0xfd, 0x6d, 0x80, 0x9b, 0xb1, 0x82, 0xdc, 0x02, 0x54,
	0x8f, 0x86, 0x0c, 0x9f, 0x3c, 0xb0, 0x90, 0xaf, 0x47, 0x67, 0x07, 0xb2, 0x22, 0xa3, 0xa7, 0x3f,
	0xfe, 0xfc, 0xfb, 0xd9, 0xe8, 0x91, 0xae, 0x6f, 0x4d, 0xf8, 0x0e, 0xbd, 0xda, 0x65, 0x91, 0x17,
	0xe6, 0xe7, 0xfd, 0x07, 0x30, 0xf2, 0x0e, 0x17, 0x44, 0x46, 0x5f, 0xe2, 0xe0, 0x53, 0xda, 0xf7,
	0x6b, 0xb5, 0x6b, 0x67, 0xaa, 0xec, 0x56, 0xf7, 0x53, 0xda, 0xad, 0xdd, 0x69, 0x69, 0xb7, 0x7e,
	0x91, 0x3b, 0xbb, 0xd3, 0xae, 0x6f, 0x4d, 0xf8, 0x02, 0x50, 0xe1, 0x2b, 0xe7, 0xd5, 0xae, 0xb2,
	0x9c, 0x57, 0xe7, 0x4c, 0xcf, 0x71, 0xde, 0x80, 0x76, 0xfd, 0xaa, 0x70, 0xed, 0x4c, 0xef, 0xdb,
	0xd8, 0xfd, 0xf6, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x71, 0x50, 0x06, 0xf3, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PayClient is the client API for Pay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayClient interface {
	//获取支付订单列表
	GetPayList(ctx context.Context, in *GetPayListReq, opts ...grpc.CallOption) (*GetPayListResp, error)
	//创建支付订单
	CreatePayInfo(ctx context.Context, in *CreatePayInfoReq, opts ...grpc.CallOption) (*CreatePayInfoResp, error)
	//删除支付订单
	DelPayInfo(ctx context.Context, in *DelPayInfoReq, opts ...grpc.CallOption) (*DelPayInfoResp, error)
	//支付支付提交
	PaySuccess(ctx context.Context, in *PaySuccessReq, opts ...grpc.CallOption) (*PaySuccessResp, error)
}

type payClient struct {
	cc *grpc.ClientConn
}

func NewPayClient(cc *grpc.ClientConn) PayClient {
	return &payClient{cc}
}

func (c *payClient) GetPayList(ctx context.Context, in *GetPayListReq, opts ...grpc.CallOption) (*GetPayListResp, error) {
	out := new(GetPayListResp)
	err := c.cc.Invoke(ctx, "/proto.pay/GetPayList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payClient) CreatePayInfo(ctx context.Context, in *CreatePayInfoReq, opts ...grpc.CallOption) (*CreatePayInfoResp, error) {
	out := new(CreatePayInfoResp)
	err := c.cc.Invoke(ctx, "/proto.pay/CreatePayInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payClient) DelPayInfo(ctx context.Context, in *DelPayInfoReq, opts ...grpc.CallOption) (*DelPayInfoResp, error) {
	out := new(DelPayInfoResp)
	err := c.cc.Invoke(ctx, "/proto.pay/DelPayInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payClient) PaySuccess(ctx context.Context, in *PaySuccessReq, opts ...grpc.CallOption) (*PaySuccessResp, error) {
	out := new(PaySuccessResp)
	err := c.cc.Invoke(ctx, "/proto.pay/PaySuccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayServer is the server API for Pay service.
type PayServer interface {
	//获取支付订单列表
	GetPayList(context.Context, *GetPayListReq) (*GetPayListResp, error)
	//创建支付订单
	CreatePayInfo(context.Context, *CreatePayInfoReq) (*CreatePayInfoResp, error)
	//删除支付订单
	DelPayInfo(context.Context, *DelPayInfoReq) (*DelPayInfoResp, error)
	//支付支付提交
	PaySuccess(context.Context, *PaySuccessReq) (*PaySuccessResp, error)
}

func RegisterPayServer(s *grpc.Server, srv PayServer) {
	s.RegisterService(&_Pay_serviceDesc, srv)
}

func _Pay_GetPayList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServer).GetPayList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.pay/GetPayList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServer).GetPayList(ctx, req.(*GetPayListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pay_CreatePayInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePayInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServer).CreatePayInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.pay/CreatePayInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServer).CreatePayInfo(ctx, req.(*CreatePayInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pay_DelPayInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPayInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServer).DelPayInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.pay/DelPayInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServer).DelPayInfo(ctx, req.(*DelPayInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pay_PaySuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaySuccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServer).PaySuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.pay/PaySuccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServer).PaySuccess(ctx, req.(*PaySuccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pay_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.pay",
	HandlerType: (*PayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayList",
			Handler:    _Pay_GetPayList_Handler,
		},
		{
			MethodName: "CreatePayInfo",
			Handler:    _Pay_CreatePayInfo_Handler,
		},
		{
			MethodName: "DelPayInfo",
			Handler:    _Pay_DelPayInfo_Handler,
		},
		{
			MethodName: "PaySuccess",
			Handler:    _Pay_PaySuccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pay.proto",
}
