// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/refund.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRefundReq struct {
	// 返回数量
	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// 返回数据开始数
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// 退款订单ID
	ID int64 `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	// 退款订单状态
	Status int64 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 支付订单ID
	PID int64 `protobuf:"varint,5,opt,name=PID,proto3" json:"PID,omitempty"`
	// 订单ID
	OID int64 `protobuf:"varint,6,opt,name=OID,proto3" json:"OID,omitempty"`
	// 退款方式 1银行卡 2支付宝 3微信
	Way int64 `protobuf:"varint,7,opt,name=way,proto3" json:"way,omitempty"`
	// 开始时间
	StartTime int64 `protobuf:"varint,8,opt,name=startTime,proto3" json:"startTime,omitempty"`
	// 结束时间
	EndTime              int64    `protobuf:"varint,9,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRefundReq) Reset()         { *m = GetRefundReq{} }
func (m *GetRefundReq) String() string { return proto.CompactTextString(m) }
func (*GetRefundReq) ProtoMessage()    {}
func (*GetRefundReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_619edb2f475a7e65, []int{0}
}

func (m *GetRefundReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRefundReq.Unmarshal(m, b)
}
func (m *GetRefundReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRefundReq.Marshal(b, m, deterministic)
}
func (m *GetRefundReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRefundReq.Merge(m, src)
}
func (m *GetRefundReq) XXX_Size() int {
	return xxx_messageInfo_GetRefundReq.Size(m)
}
func (m *GetRefundReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRefundReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRefundReq proto.InternalMessageInfo

func (m *GetRefundReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetRefundReq) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetRefundReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GetRefundReq) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetRefundReq) GetPID() int64 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *GetRefundReq) GetOID() int64 {
	if m != nil {
		return m.OID
	}
	return 0
}

func (m *GetRefundReq) GetWay() int64 {
	if m != nil {
		return m.Way
	}
	return 0
}

func (m *GetRefundReq) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GetRefundReq) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type GetRefundResp struct {
	// 返回码 200:成功 500:失败
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// 错误信息
	Err string `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	// 检索数据总数
	Allnum int64 `protobuf:"varint,3,opt,name=Allnum,proto3" json:"Allnum,omitempty"`
	// 数据数列
	Data                 []*GetRefundInfo `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetRefundResp) Reset()         { *m = GetRefundResp{} }
func (m *GetRefundResp) String() string { return proto.CompactTextString(m) }
func (*GetRefundResp) ProtoMessage()    {}
func (*GetRefundResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_619edb2f475a7e65, []int{1}
}

func (m *GetRefundResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRefundResp.Unmarshal(m, b)
}
func (m *GetRefundResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRefundResp.Marshal(b, m, deterministic)
}
func (m *GetRefundResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRefundResp.Merge(m, src)
}
func (m *GetRefundResp) XXX_Size() int {
	return xxx_messageInfo_GetRefundResp.Size(m)
}
func (m *GetRefundResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRefundResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRefundResp proto.InternalMessageInfo

func (m *GetRefundResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetRefundResp) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetRefundResp) GetAllnum() int64 {
	if m != nil {
		return m.Allnum
	}
	return 0
}

func (m *GetRefundResp) GetData() []*GetRefundInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetRefundInfo struct {
	// 退款订单ID
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// 商品订单ID
	OID int64 `protobuf:"varint,2,opt,name=OID,proto3" json:"OID,omitempty"`
	// 商品支付金额
	Oprice int64 `protobuf:"varint,3,opt,name=oprice,proto3" json:"oprice,omitempty"`
	// 退款金额
	Price int64 `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`
	// 退款方式 1银行卡 2支付宝 3微信
	Way int64 `protobuf:"varint,5,opt,name=Way,proto3" json:"Way,omitempty"`
	// 退款账号
	Number string `protobuf:"bytes,6,opt,name=Number,proto3" json:"Number,omitempty"`
	// 退款状态
	Status int64 `protobuf:"varint,7,opt,name=Status,proto3" json:"Status,omitempty"`
	// 创建时间
	CreateTime           int64    `protobuf:"varint,8,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRefundInfo) Reset()         { *m = GetRefundInfo{} }
func (m *GetRefundInfo) String() string { return proto.CompactTextString(m) }
func (*GetRefundInfo) ProtoMessage()    {}
func (*GetRefundInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_619edb2f475a7e65, []int{2}
}

func (m *GetRefundInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRefundInfo.Unmarshal(m, b)
}
func (m *GetRefundInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRefundInfo.Marshal(b, m, deterministic)
}
func (m *GetRefundInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRefundInfo.Merge(m, src)
}
func (m *GetRefundInfo) XXX_Size() int {
	return xxx_messageInfo_GetRefundInfo.Size(m)
}
func (m *GetRefundInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRefundInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GetRefundInfo proto.InternalMessageInfo

func (m *GetRefundInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GetRefundInfo) GetOID() int64 {
	if m != nil {
		return m.OID
	}
	return 0
}

func (m *GetRefundInfo) GetOprice() int64 {
	if m != nil {
		return m.Oprice
	}
	return 0
}

func (m *GetRefundInfo) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GetRefundInfo) GetWay() int64 {
	if m != nil {
		return m.Way
	}
	return 0
}

func (m *GetRefundInfo) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *GetRefundInfo) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetRefundInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type CreateReFundReq struct {
	// 商品订单ID
	OID int64 `protobuf:"varint,1,opt,name=OID,proto3" json:"OID,omitempty"`
	// 退款方式 1银行卡 2支付宝 3微信
	Way int64 `protobuf:"varint,2,opt,name=way,proto3" json:"way,omitempty"`
	// 退款账号
	Number string `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	// 退款金额
	Price                int64    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReFundReq) Reset()         { *m = CreateReFundReq{} }
func (m *CreateReFundReq) String() string { return proto.CompactTextString(m) }
func (*CreateReFundReq) ProtoMessage()    {}
func (*CreateReFundReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_619edb2f475a7e65, []int{3}
}

func (m *CreateReFundReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReFundReq.Unmarshal(m, b)
}
func (m *CreateReFundReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReFundReq.Marshal(b, m, deterministic)
}
func (m *CreateReFundReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReFundReq.Merge(m, src)
}
func (m *CreateReFundReq) XXX_Size() int {
	return xxx_messageInfo_CreateReFundReq.Size(m)
}
func (m *CreateReFundReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReFundReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReFundReq proto.InternalMessageInfo

func (m *CreateReFundReq) GetOID() int64 {
	if m != nil {
		return m.OID
	}
	return 0
}

func (m *CreateReFundReq) GetWay() int64 {
	if m != nil {
		return m.Way
	}
	return 0
}

func (m *CreateReFundReq) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *CreateReFundReq) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CreateReFundResp struct {
	// 返回码 200:成功 500:失败
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// 错误信息
	Err string `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	// 退款订单ID
	ID                   int64    `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReFundResp) Reset()         { *m = CreateReFundResp{} }
func (m *CreateReFundResp) String() string { return proto.CompactTextString(m) }
func (*CreateReFundResp) ProtoMessage()    {}
func (*CreateReFundResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_619edb2f475a7e65, []int{4}
}

func (m *CreateReFundResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReFundResp.Unmarshal(m, b)
}
func (m *CreateReFundResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReFundResp.Marshal(b, m, deterministic)
}
func (m *CreateReFundResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReFundResp.Merge(m, src)
}
func (m *CreateReFundResp) XXX_Size() int {
	return xxx_messageInfo_CreateReFundResp.Size(m)
}
func (m *CreateReFundResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReFundResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReFundResp proto.InternalMessageInfo

func (m *CreateReFundResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateReFundResp) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *CreateReFundResp) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DelRefundReq struct {
	// 退款订单ID
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelRefundReq) Reset()         { *m = DelRefundReq{} }
func (m *DelRefundReq) String() string { return proto.CompactTextString(m) }
func (*DelRefundReq) ProtoMessage()    {}
func (*DelRefundReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_619edb2f475a7e65, []int{5}
}

func (m *DelRefundReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelRefundReq.Unmarshal(m, b)
}
func (m *DelRefundReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelRefundReq.Marshal(b, m, deterministic)
}
func (m *DelRefundReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelRefundReq.Merge(m, src)
}
func (m *DelRefundReq) XXX_Size() int {
	return xxx_messageInfo_DelRefundReq.Size(m)
}
func (m *DelRefundReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelRefundReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelRefundReq proto.InternalMessageInfo

func (m *DelRefundReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DelRefundResp struct {
	// 返回码 200:成功 500:失败
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// 错误信息
	Err                  string   `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelRefundResp) Reset()         { *m = DelRefundResp{} }
func (m *DelRefundResp) String() string { return proto.CompactTextString(m) }
func (*DelRefundResp) ProtoMessage()    {}
func (*DelRefundResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_619edb2f475a7e65, []int{6}
}

func (m *DelRefundResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelRefundResp.Unmarshal(m, b)
}
func (m *DelRefundResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelRefundResp.Marshal(b, m, deterministic)
}
func (m *DelRefundResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelRefundResp.Merge(m, src)
}
func (m *DelRefundResp) XXX_Size() int {
	return xxx_messageInfo_DelRefundResp.Size(m)
}
func (m *DelRefundResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelRefundResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelRefundResp proto.InternalMessageInfo

func (m *DelRefundResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DelRefundResp) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type RefundSuccessReq struct {
	// 退款订单ID
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// 退款金额
	Price int64 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	// 退款方式 1银行卡 2支付宝 3微信
	Way int64 `protobuf:"varint,3,opt,name=way,proto3" json:"way,omitempty"`
	// 退款账号
	Number string `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	// 退款流水号
	Serial               string   `protobuf:"bytes,5,opt,name=serial,proto3" json:"serial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefundSuccessReq) Reset()         { *m = RefundSuccessReq{} }
func (m *RefundSuccessReq) String() string { return proto.CompactTextString(m) }
func (*RefundSuccessReq) ProtoMessage()    {}
func (*RefundSuccessReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_619edb2f475a7e65, []int{7}
}

func (m *RefundSuccessReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundSuccessReq.Unmarshal(m, b)
}
func (m *RefundSuccessReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundSuccessReq.Marshal(b, m, deterministic)
}
func (m *RefundSuccessReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundSuccessReq.Merge(m, src)
}
func (m *RefundSuccessReq) XXX_Size() int {
	return xxx_messageInfo_RefundSuccessReq.Size(m)
}
func (m *RefundSuccessReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundSuccessReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefundSuccessReq proto.InternalMessageInfo

func (m *RefundSuccessReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RefundSuccessReq) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *RefundSuccessReq) GetWay() int64 {
	if m != nil {
		return m.Way
	}
	return 0
}

func (m *RefundSuccessReq) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *RefundSuccessReq) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

type RefundSuccessResp struct {
	// 返回码 200:成功 500:失败
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// 错误信息
	Err                  string   `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefundSuccessResp) Reset()         { *m = RefundSuccessResp{} }
func (m *RefundSuccessResp) String() string { return proto.CompactTextString(m) }
func (*RefundSuccessResp) ProtoMessage()    {}
func (*RefundSuccessResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_619edb2f475a7e65, []int{8}
}

func (m *RefundSuccessResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundSuccessResp.Unmarshal(m, b)
}
func (m *RefundSuccessResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundSuccessResp.Marshal(b, m, deterministic)
}
func (m *RefundSuccessResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundSuccessResp.Merge(m, src)
}
func (m *RefundSuccessResp) XXX_Size() int {
	return xxx_messageInfo_RefundSuccessResp.Size(m)
}
func (m *RefundSuccessResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundSuccessResp.DiscardUnknown(m)
}

var xxx_messageInfo_RefundSuccessResp proto.InternalMessageInfo

func (m *RefundSuccessResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RefundSuccessResp) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRefundReq)(nil), "proto.GetRefundReq")
	proto.RegisterType((*GetRefundResp)(nil), "proto.GetRefundResp")
	proto.RegisterType((*GetRefundInfo)(nil), "proto.GetRefundInfo")
	proto.RegisterType((*CreateReFundReq)(nil), "proto.CreateReFundReq")
	proto.RegisterType((*CreateReFundResp)(nil), "proto.CreateReFundResp")
	proto.RegisterType((*DelRefundReq)(nil), "proto.DelRefundReq")
	proto.RegisterType((*DelRefundResp)(nil), "proto.DelRefundResp")
	proto.RegisterType((*RefundSuccessReq)(nil), "proto.RefundSuccessReq")
	proto.RegisterType((*RefundSuccessResp)(nil), "proto.RefundSuccessResp")
}

func init() { proto.RegisterFile("proto/refund.proto", fileDescriptor_619edb2f475a7e65) }

var fileDescriptor_619edb2f475a7e65 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6e, 0xda, 0x40,
	0x14, 0x96, 0x6d, 0x20, 0xe5, 0x35, 0xa1, 0x64, 0x82, 0xa8, 0x8b, 0x50, 0x14, 0xcd, 0x0a, 0xb1,
	0x88, 0xa5, 0x54, 0x5d, 0x34, 0xbb, 0x2a, 0xee, 0x0f, 0x52, 0xd5, 0x44, 0x93, 0x4a, 0x59, 0x75,
	0x31, 0x81, 0x21, 0xb2, 0x64, 0x6c, 0xc7, 0x33, 0x08, 0xd1, 0x65, 0xaf, 0xd0, 0x13, 0xf5, 0x0a,
	0xed, 0x15, 0x7a, 0x82, 0x9e, 0xa0, 0x9a, 0x37, 0x63, 0xb0, 0x1d, 0x16, 0xac, 0x98, 0xef, 0x9b,
	0x79, 0x7f, 0xdf, 0xf7, 0x30, 0x90, 0x2c, 0x4f, 0x55, 0x1a, 0xe4, 0x62, 0xbe, 0x4c, 0x66, 0xe7,
	0x08, 0x48, 0x13, 0x7f, 0x06, 0xc3, 0x87, 0x34, 0x7d, 0x88, 0x45, 0xc0, 0xb3, 0x28, 0xe0, 0x49,
	0x92, 0x2a, 0xae, 0xa2, 0x34, 0x91, 0xe6, 0x11, 0xfd, 0xed, 0xc0, 0xe1, 0x47, 0xa1, 0x18, 0x06,
	0x32, 0xf1, 0x48, 0x7a, 0xd0, 0x8c, 0xa3, 0x45, 0xa4, 0x7c, 0xe7, 0xcc, 0x19, 0x79, 0xcc, 0x00,
	0xd2, 0x87, 0x56, 0x3a, 0x9f, 0x4b, 0xa1, 0x7c, 0x17, 0x69, 0x8b, 0x48, 0x07, 0xdc, 0x49, 0xe8,
	0x7b, 0xc8, 0xb9, 0x93, 0x50, 0xbf, 0x93, 0x8a, 0xab, 0xa5, 0xf4, 0x1b, 0xe6, 0x9d, 0x41, 0xa4,
	0x0b, 0xde, 0xcd, 0x24, 0xf4, 0x9b, 0x48, 0xea, 0xa3, 0x66, 0xae, 0x27, 0xa1, 0xdf, 0x32, 0xcc,
	0xb5, 0x61, 0x56, 0x7c, 0xed, 0x1f, 0x18, 0x66, 0xc5, 0xd7, 0x64, 0x08, 0x6d, 0xa9, 0x78, 0xae,
	0xbe, 0x46, 0x0b, 0xe1, 0x3f, 0x43, 0x7e, 0x4b, 0x10, 0x1f, 0x0e, 0x44, 0x32, 0xc3, 0xbb, 0x36,
	0xde, 0x15, 0x90, 0xae, 0xe0, 0xa8, 0x34, 0x93, 0xcc, 0x08, 0x81, 0xc6, 0x55, 0x3a, 0x13, 0x38,
	0x53, 0x93, 0xe1, 0x59, 0x97, 0x7b, 0x9f, 0xe7, 0x38, 0x4f, 0x9b, 0xe9, 0xa3, 0x6e, 0xfe, 0x5d,
	0x1c, 0x27, 0xcb, 0x85, 0x1d, 0xc8, 0x22, 0x32, 0x82, 0x46, 0xc8, 0x15, 0xf7, 0x1b, 0x67, 0xde,
	0xe8, 0xf9, 0x45, 0xcf, 0x28, 0x77, 0xbe, 0xa9, 0x30, 0x49, 0xe6, 0x29, 0xc3, 0x17, 0xf4, 0x97,
	0x53, 0xaa, 0xac, 0x79, 0x2b, 0x90, 0xb3, 0x11, 0xc8, 0x8e, 0xed, 0x6e, 0xc7, 0xd6, 0xd2, 0x66,
	0x79, 0x34, 0x15, 0x45, 0x55, 0x83, 0xb4, 0x11, 0x37, 0x48, 0x1b, 0x25, 0x0d, 0xd0, 0xf1, 0x77,
	0x7c, 0x5d, 0x08, 0x79, 0xc7, 0xd7, 0x3a, 0xfe, 0xcb, 0x72, 0x71, 0x2f, 0x72, 0xd4, 0xb2, 0xcd,
	0x2c, 0xd2, 0xfc, 0xad, 0xb1, 0xc2, 0x28, 0x6a, 0x11, 0x39, 0x05, 0xb8, 0xca, 0x05, 0x57, 0xa2,
	0xa4, 0x6a, 0x89, 0xa1, 0x53, 0x78, 0x61, 0x10, 0x13, 0x1f, 0xec, 0x4e, 0xd8, 0xa6, 0x9d, 0x27,
	0x5e, 0xb9, 0x5b, 0xaf, 0xfa, 0xd0, 0x4a, 0x4c, 0x1b, 0x9e, 0x69, 0xc3, 0x20, 0x3d, 0x46, 0x56,
	0x1e, 0x03, 0x01, 0xfd, 0x04, 0xdd, 0x6a, 0x91, 0xbd, 0x4d, 0xaa, 0x6d, 0x1c, 0x3d, 0x85, 0xc3,
	0x50, 0xc4, 0xdb, 0xfd, 0xad, 0x09, 0x4e, 0xdf, 0xc0, 0x51, 0xe9, 0x7e, 0xdf, 0x32, 0xf4, 0x3b,
	0x74, 0x4d, 0xcc, 0xed, 0x72, 0x3a, 0x15, 0x52, 0xee, 0x48, 0xbd, 0x1d, 0xcd, 0x2d, 0x8d, 0x56,
	0x48, 0xe3, 0xed, 0x92, 0xa6, 0x51, 0x91, 0x46, 0xff, 0x59, 0x44, 0x1e, 0xf1, 0x18, 0xed, 0x6c,
	0x33, 0x8b, 0xe8, 0x5b, 0x38, 0xae, 0xd5, 0xde, 0xb7, 0xed, 0x8b, 0x7f, 0x2e, 0xb4, 0xcc, 0x47,
	0x80, 0xb0, 0xfa, 0x2a, 0x9e, 0xd4, 0x17, 0x97, 0x89, 0xc7, 0x41, 0xef, 0x29, 0x29, 0x33, 0xda,
	0xff, 0xf1, 0xe7, 0xef, 0x4f, 0xb7, 0x4b, 0x3a, 0xc1, 0x86, 0xff, 0x1c, 0x49, 0x45, 0x78, 0xd5,
	0x36, 0x4c, 0xdb, 0xb7, 0x19, 0x6a, 0x4b, 0x33, 0x78, 0xb9, 0x93, 0x97, 0x19, 0x1d, 0x62, 0xf2,
	0x3e, 0x3d, 0x0e, 0xea, 0xb9, 0x2e, 0x9d, 0xb1, 0x6e, 0x7b, 0xe3, 0x57, 0x54, 0x6e, 0xbb, 0xec,
	0xf2, 0xa6, 0xed, 0x8a, 0xb5, 0x45, 0xdb, 0xe3, 0x4e, 0x50, 0x4d, 0xf1, 0x0d, 0x8e, 0x2a, 0x82,
	0x92, 0xa2, 0xb7, 0xba, 0xc5, 0x03, 0x7f, 0xf7, 0x85, 0xcc, 0xe8, 0x2b, 0xcc, 0x7d, 0x42, 0x3b,
	0x41, 0xe5, 0xee, 0xd2, 0x19, 0xdf, 0xb7, 0x30, 0xe6, 0xf5, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0xda, 0x22, 0x83, 0x85, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RefundClient is the client API for Refund service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RefundClient interface {
	//获取退款列表
	GetRefundInfo(ctx context.Context, in *GetRefundReq, opts ...grpc.CallOption) (*GetRefundResp, error)
	//提交退款订单
	CreateReFundInfo(ctx context.Context, in *CreateReFundReq, opts ...grpc.CallOption) (*CreateReFundResp, error)
	//删除退款订单
	DelRefundinfo(ctx context.Context, in *DelRefundReq, opts ...grpc.CallOption) (*DelRefundResp, error)
	//提交成功退款
	RefundSuccess(ctx context.Context, in *RefundSuccessReq, opts ...grpc.CallOption) (*RefundSuccessResp, error)
}

type refundClient struct {
	cc *grpc.ClientConn
}

func NewRefundClient(cc *grpc.ClientConn) RefundClient {
	return &refundClient{cc}
}

func (c *refundClient) GetRefundInfo(ctx context.Context, in *GetRefundReq, opts ...grpc.CallOption) (*GetRefundResp, error) {
	out := new(GetRefundResp)
	err := c.cc.Invoke(ctx, "/proto.refund/GetRefundInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundClient) CreateReFundInfo(ctx context.Context, in *CreateReFundReq, opts ...grpc.CallOption) (*CreateReFundResp, error) {
	out := new(CreateReFundResp)
	err := c.cc.Invoke(ctx, "/proto.refund/CreateReFundInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundClient) DelRefundinfo(ctx context.Context, in *DelRefundReq, opts ...grpc.CallOption) (*DelRefundResp, error) {
	out := new(DelRefundResp)
	err := c.cc.Invoke(ctx, "/proto.refund/DelRefundinfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundClient) RefundSuccess(ctx context.Context, in *RefundSuccessReq, opts ...grpc.CallOption) (*RefundSuccessResp, error) {
	out := new(RefundSuccessResp)
	err := c.cc.Invoke(ctx, "/proto.refund/RefundSuccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RefundServer is the server API for Refund service.
type RefundServer interface {
	//获取退款列表
	GetRefundInfo(context.Context, *GetRefundReq) (*GetRefundResp, error)
	//提交退款订单
	CreateReFundInfo(context.Context, *CreateReFundReq) (*CreateReFundResp, error)
	//删除退款订单
	DelRefundinfo(context.Context, *DelRefundReq) (*DelRefundResp, error)
	//提交成功退款
	RefundSuccess(context.Context, *RefundSuccessReq) (*RefundSuccessResp, error)
}

func RegisterRefundServer(s *grpc.Server, srv RefundServer) {
	s.RegisterService(&_Refund_serviceDesc, srv)
}

func _Refund_GetRefundInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundServer).GetRefundInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.refund/GetRefundInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundServer).GetRefundInfo(ctx, req.(*GetRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Refund_CreateReFundInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReFundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundServer).CreateReFundInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.refund/CreateReFundInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundServer).CreateReFundInfo(ctx, req.(*CreateReFundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Refund_DelRefundinfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundServer).DelRefundinfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.refund/DelRefundinfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundServer).DelRefundinfo(ctx, req.(*DelRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Refund_RefundSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundSuccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundServer).RefundSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.refund/RefundSuccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundServer).RefundSuccess(ctx, req.(*RefundSuccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Refund_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.refund",
	HandlerType: (*RefundServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRefundInfo",
			Handler:    _Refund_GetRefundInfo_Handler,
		},
		{
			MethodName: "CreateReFundInfo",
			Handler:    _Refund_CreateReFundInfo_Handler,
		},
		{
			MethodName: "DelRefundinfo",
			Handler:    _Refund_DelRefundinfo_Handler,
		},
		{
			MethodName: "RefundSuccess",
			Handler:    _Refund_RefundSuccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/refund.proto",
}
